### ISSUE TITLE
Nasty stack hack에서 rsp가 16의 배수가 되야해요

### ISSUE THREAD

**Issue by 0xrgb** [koosaga/DeobureoMinkyuParty#1]
```cpp
void* newstack = malloc(sz);
//void *sp_dest = newstack + sz - sizeof(void*);
void *sp_dest = (void*)((uintptr_t(newstack) + sz - sizeof(void*)) & ~uintptr_t(15));
```

[glibc malloc](http://www.delorie.com/gnu/docs/glibc/libc_31.html) 은 8/16의 배수 값을 항상 돌려주기 때문에 상관은 없지만, 동작이 바뀔 수도 있어요.

function call 할 때 align이 안되어있으면 에러가 생길 수 있어요.
32비트면 8비트 align만 요구하니까, 그냥 써도 되고, 15를 7로 바꿔도 됩니다.

**Comment by koosaga** [comment]
알려주셔서 감사합니다.

g++ 환경을 가정하지 않으면 이미 저희 팀노트의 수많은 부분에서 문제가 발생해서, 저 부분은 현행 유지하겠습니다.
